### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by dtyi01** [THUrssq/Tianchi04#11]
Hello, I encountered the following issues while trying to reproduce your code using mmcv and mmdet. Could you please explain the reasons for this and suggest how to resolve them?

Traceback (most recent call last):
  File "attack_1.py", line 146, in <module>
    mask = get_mask(data['img'], data['img_metas'], pixels)
  File "attack_1.py", line 71, in get_mask
    bbox, label = model2(return_loss=False, rescale=True, img=image, img_metas=meta)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by dtyi01** [comment]
> Hello, I encountered the following issues while trying to reproduce your code using mmcv and mmdet. Could you please explain the reasons for this and suggest how to resolve them?
> 
> File "/public/MountData/DataDir/dty/tc04/mmdetection-2.23.0/mmdet/models/detectors/faster_rcnn.py", line 27, in **init** init_cfg=init_cfg) File "/public/MountData/DataDir/dty/tc04/mmdetection-2.23.0/mmdet/models/detectors/two_stage.py", line 40, in **init** rpn_head_.update(train_cfg=rpn_train_cfg, test_cfg=test_cfg.rpn) TypeError: update() got an unexpected keyword argument 'train_cfg'
